name: Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  my-host:  '127.0.0.1'

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo ${{vars.COMPANY_NAME}}
        - run: echo ${{env.COMPANY_NAME}}
        - run: echo "host $my-host"
        - run: echo "${{github.actor}}"
    
    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "repo ${{github.repository}} ${{env.my-host}}"
    
    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "status ${{job.status}}"
