name: Demo

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - '*feature'

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "hello world"