name: Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "${{github.actor}}"
    
    test-job:
      runs-on: ubuntu-latest
      needs: build-job
      steps:
        - run: echo "repo ${{github.repository}}"
    
    deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - run: echo "status ${{job.status}}"
